name: CD

on:
  push:
    tags:
      - "**"

env:
  IMAGE_NAME: ""
  PROJECT_ID: ""
  AR_REPO_LOCATION: ""
  AR_URL: ""
  WORKLOAD_IDENTITY_PROVIDER: ""

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get git tag
        uses: dawidd6/action-get-tag@v1
        id: tag

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: Set-up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev --quiet

      - name: Docker build
        run: |
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}" ./

      - name: Docker push
        run: |
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}"
