name: CD

on:
  push:
    tags:
      - "**"

# todo(ramon) set-up AR + Github secrets for docker CD to work
env:
  IMAGE_NAME: "personal-website"
  AR_REPO_LOCATION: ""

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get git tag
        uses: dawidd6/action-get-tag@v1
        id: tag

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ secrets.PROJECT_ID }}"
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: Set-up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        if: contains(github.ref, 'main')
        with:
          push: true
          tags: ${{ secrets.AR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.git_tag.outputs.tag }}

