name: CD

on:
  push:
    tags:
      - "**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ secrets.WIF_PROJECT_ID }}"
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: Get git tag
        uses: dawidd6/action-get-tag@v1
        id: tag

      - name: Set-up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ secrets.AR_LOCATION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # part is only triggered on a tag push (e.g. via GH release)
      - name: Build and push
        uses: docker/build-push-action@v6
        if: contains(github.ref, 'refs/tags/')
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.AR_URL }}/${{ secrets.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

